apiVersion: skaffold/v2beta2
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: petegross/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: petegross/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: petegross/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: petegross/orders
      context: orders
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: petegross/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: petegross/payments
      context: payments
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
