apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # how many pods we can add at a time
      maxUnavailable:
        0
        # maxUnavailable define how many pods can be
        # unavailable during the rolling update
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers: # wait for the mongodb to respond before starting pods
        - name: init-db
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z auth-mongo-srv:27017; do echo waiting for auth-mongo-srv; sleep 2; done;",
            ]
      containers:
        - name: auth
          image: registry.gitlab.com/microservice_example/ticketing/auth
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/users/healthz
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          env:
            - name: MONGO_URI
              value: "mongodb://auth-mongo-srv:27017/auth"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
