apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: petegross/payments:dev
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/payments/healthz
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          env:
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: ticketing # The ConfigMap this value comes from.
                  key: NATS_URL # The key to fetch.
            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: ticketing # The ConfigMap this value comes from.
                  key: NATS_CLUSTER_ID # The key to fetch.
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: "mongodb://payments-mongo-srv:27017/payments"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  type: ClusterIP
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
