apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketing
data:
  SERVER_URL_BASE: "http://my-release-ingress-nginx-controller.default.svc.cluster.local"
  NATS_URL: "http://nats-srv:4222"
  NATS_CLUSTER_ID: ticketing
  EXPIRATION_WINDOW_SECONDS: "900"
  NEXT_PUBLIC_STRIPE_KEY: "hshshshshshsh"
