apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-persistent-volume-claim
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
