apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - orders-mongo
              topologyKey: "kubernetes.io/hostname"
      initContainers: # wait for the mongodb to respond before starting pods
        - name: init-db
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z orders-mongo-srv:27017; do echo waiting for orders-mongo-srv; sleep 2; done;",
            ]
      containers:
        - name: orders
          image: registry.gitlab.com/microservice_example/ticketing/orders:prod
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/orders/healthz
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          env:
            - name: EXPIRATION_WINDOW_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: ticketing # The ConfigMap this value comes from.
                  key: EXPIRATION_WINDOW_SECONDS # The key to fetch.
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: ticketing # The ConfigMap this value comes from.
                  key: NATS_URL # The key to fetch.
            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: ticketing # The ConfigMap this value comes from.
                  key: NATS_CLUSTER_ID # The key to fetch.
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: "mongodb://orders-mongo-srv:27017/orders"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
